version: "3.8"
services:
  dev-db:
    image: postgres:13
    hostname: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: projects-portfolio
    networks:
      - projectsportfolio
    volumes:
      - docker-nest-postgres-dev:/var/lib/postgresql/data
  test-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: projects-portfolio
    networks:
      - projectsportfolio
    volumes:
      - docker-nest-postgres-test:/var/lib/postgresql/data
networks:
      projectsportfolio:
        driver: bridge
volumes:
  docker-nest-postgres-dev:
  docker-nest-postgres-test: